### ISSUE TITLE
GCS store issues

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/paste-click#35]
More insight into what went wrong would be good as well

request
```
~ # curl -X POST -d 'test' http://localhost:8001/
Unable to save object
http://localhost:8001/098f6bcd4621d373cade4e832627b4f6
```

Application logs
```
::1 - - [30/Jan/2019:06:10:47 +0000] "POST / HTTP/1.1" 500 77
```

k8s config
```
env:
            - name: ADDR
              value: ':8001'
            - name: STORAGE_DRIVER
              value: gcs
            - name: STORE_GCS_BUCKET_NAME
              value: paste-click-objects
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
```
